### ISSUE TITLE
Support new macaroon format

### ISSUE THREAD

**Issue by ecordell** [ecordell/pymacaroons#22]
https://groups.google.com/forum/#!topic/macaroons/EIDUZQoelq8

**Comment by rogpeppe** [comment]
We're about to do some work on this. Just commenting in case anyone is currently working on it.

**Comment by ecordell** [comment]
Thanks for the heads up @rogpeppe, is the discussion somewhere I can track?

**Comment by rogpeppe** [comment]
Thus far discussion has only been verbal. In general I am inclined to follow the general direction I used in gopkg.in/macaroon.v2-unstable, making the version a visible part of the API, because not all v2 macaroons can be represented in v1 formats.

**Comment by fabricematrat** [comment]
I think the main changes are the identifier for macaroon and caveat can be pure binary format which means you can't use the convert_to_string on the identifier getter.
The serialization to JSON can be in the following format for example:

https://gist.github.com/fabricematrat/531b49b834bdcfa8e887e2087c93e531

I didn't do the deserializtion.
I think other libraries do support base64 encoding/decoding without padding and I think it would be better to use utf-8 encoding instead of ascii in the converter.

A few things also would have to change like the inspect method which can't return a string.

**Comment by ecordell** [comment]
Close by #28 . Thanks @fabricematrat!
