### ISSUE TITLE
verification does not use root macaroon signature in bind

### ISSUE THREAD

**Issue by rogpeppe** [ecordell/pymacaroons#37]
In the original macaroons paper, PrepareForRequest binds the signature of all the discharge macaroons to the root macaroon's signature. Pymacaroons does not do that when verifying macaroons more than one level deep - instead it binds the signature of the discharge macaroon to that of its parent. This is different (and incompatible) behaviour from that expected by libmacaroons and the Go macaroons implementation.

The following code demonstrates the issue. It uses both libmacaroons and pymacaroons to demonstrate the incompatibility, but the issue can adequately be demonstrated with pymacaroons alone.

	import pymacaroons
	import base64
	import json
	import macaroons
	
	def testpymacaroons():
	    print('test pymacaroons')
	    # Create a root macaroon with discharge.
	    root = pymacaroons.Macaroon(location="", identifier="root-id", key="root-key")
	    root.add_third_party_caveat("bob", "bob-caveat-root-key", "bob-is-great")
	    
	    # Create a discharge macaroon that requires a secondary discharge.
	    discharge1 = pymacaroons.Macaroon(location="bob", identifier="bob-is-great", key="bob-caveat-root-key")
	    discharge1.add_third_party_caveat("barbara", "barbara-caveat-root-key", "barbara-is-great")
	    
	    # Create the secondary discharge macaroon.
	    discharge2 = pymacaroons.Macaroon(location="barbara", identifier="barbara-is-great", key="barbara-caveat-root-key")
	    
	    # Prepare the discharge macaroons for request.
	    discharge1 = root.prepare_for_request(discharge1)
	    discharge2 = root.prepare_for_request(discharge2)
	    
	    # verification fails with MacaroonInvalidSignatureException.
	    try:
	        pymacaroons.Verifier().verify(root, "root-key", [discharge1, discharge2])
	        print('pymacaroons verifed ok')
	    except Exception as e:
	        print('pymacaroons verification failed: {}'.format(e))

	    # libmacaroons succeeds in verifying the same
	    # macaroons that pymacaroons failed on.
	    l_root = macaroons.deserialize(bytes(root.serialize()))
	    l_discharge1 = macaroons.deserialize(bytes(discharge1.serialize()))
	    l_discharge2 = macaroons.deserialize(bytes(discharge2.serialize()))
	
	    try:
	        macaroons.Verifier().verify(l_root, "root-key", [l_discharge1, l_discharge2])
	        print('libmacaroons verified ok after deserialization')
	    except Exception as e:
	        print('libmacaroons verification failed: {}'.format(e))
	
	def testlibmacaroons():
	    print('test libmacaroons')
	    # Create a root macaroon with discharge.
	    root = macaroons.create("", "root-key", "root-id")
	    root = root.add_third_party_caveat("bob", "bob-caveat-root-key", "bob-is-great")
	    
	    # Create a discharge macaroon that requires a secondary discharge.
	    discharge1 = macaroons.create("bob", "bob-caveat-root-key", "bob-is-great")
	    discharge1 = discharge1.add_third_party_caveat("babara", "barbara-caveat-root-key", "barbara-is-great")
	    
	    # Create the secondary discharge macaroon.
	    discharge2 = macaroons.create("barbara", "barbara-caveat-root-key", "barbara-is-great")
	    
	    # Prepare the discharge macaroons for request.
	    discharge1 = root.prepare_for_request(discharge1)
	    discharge2 = root.prepare_for_request(discharge2)

	    # verification succeeds ok.
	    macaroons.Verifier().verify(root, "root-key", [discharge1, discharge2])
	    
	    print('libmacaroons verified ok')

	    # pymacaroons fails to verify the macaroons that libmacaroons succeeded
	    # in verifying
	    p_root = pymacaroons.Macaroon.deserialize(root.serialize(format=1))
	    p_discharge1 = pymacaroons.Macaroon.deserialize(discharge1.serialize(format=1))
	    p_discharge2 = pymacaroons.Macaroon.deserialize(discharge2.serialize(format=1))
	
	    try:
	        pymacaroons.Verifier().verify(p_root, "root-key", [p_discharge1, p_discharge2])
	        print('pymacaroons verified ok after deserialization')
	    except Exception as e:
	        print('pymacaroons verification failed: {}'.format(e))
	
	testpymacaroons()
	testlibmacaroons()

**Comment by ecordell** [comment]
Thanks @rogpeppe for finding this incompatibility.

The way I've understood macaroon trees is that we should bind in this way:

```python
    # Prepare the discharge macaroons for request.
    discharge1 = root.prepare_for_request(discharge1)
    discharge2 = discharge1.prepare_for_request(discharge2)
```

(which will validate fine with pymacaroons)

This makes sense to me because discharges are points at which different entities can make assertions. Discharges are encapsulation points, if you will.

If we bind sub-discharges to the "root" instead of the "parent", then I think we have the situation that the paper warns about where discharges can potentially be used to discharge third party caveats they weren't intended to (discharge2 *should* only be used to discharge the third party caveat in discharge1, but because it has to be given "unbound" to the root owner, if intercepted it can be rebound to something other than discharge1). 

I don't see any difference in the security guarantees of the model used here, but that could definitely be a reason to change it. Otherwise it seems to me like the way it's currently implemented aligns with the intended use of discharge macaroons. 

What do you think? Do you buy this argument? 

Also, is there some property of binding all of the discharges to the root that you're relying on for a particular application?

If so, we might actually want both:

```python
    discharge1 = root.prepare_for_request(discharge1)
    discharge2 = root.prepare_for_request(discharge1.prepare_for_request(discharge2))
```

**Comment by rogpeppe** [comment]
> What do you think? Do you buy this argument?

In general, I think we should be following the macaroon algorithms specified in the paper.

Here's the relevant snippet from the paper. Here M is the root macaroon and 𝓜 is the set of discharge macaroons. Note that it uses the same M for all discharge macaroons, and that *all* discharge macaroons are in 𝓜, not just the discharges for the top level macaroon.

    M.PrepareForRequest(𝓜)
        𝓜sealed := ∅
        for M' ∈ 𝓜
            macaroon@L'<id', C' , sig'> ← M'
            sig'' := M.bindForRequest(sig')
            𝓜sealed := 𝓜sealed ∪ {macaroon@L'<id' , C' , sig''>}
        return 𝓜sealed

This is borne out by the way that Verify is specified. Note that even though Verify is called recursively, the same TM is used throughout (this is the difference from the current pymacaroons behaviour).

    M.Verify(TM , k, 𝒜, 𝓜)
        cSig := MAC(k, M.id )
        for i := 0 to |M.C| − 1
            ...
            assert (∃M' ∈ 𝓜 : M'.id = cId ∧ M'.Verify(TM, cK, 𝒜, 𝓜))
            ...
        assert (M.sig = TM.bindForRequest(cSig))
        return true

Here's the paper describing how Verify is used:

> In order to verify an incoming access request consisting of an authorizing macaroon TM and a set of discharge macaroons 𝓜, a target service must ensure that all first-party and third-party caveats embedded in either TM or any macaroon in 𝓜 are satisfied.
> [...]
> To authorize the request, the target service invokes the method TM.Verify(TM, k, 𝒜, 𝓜) where k is the root key of macaroon TM.

Note that 𝓜 contains *all* the discharge macaroons, not just the discharge macaroons for the root macaroon, and observe that the same root signature is used to bind all those macaroons, because the same TM is used for all calls to bindForRequest, regardless of the level of recursion.

I don't really want to get into discussing whether this behaviour is correct or not from a security point of view; I am not a security expert - I trust the intuition and proofs of the paper's authors, and I don't think we should deviate from the algorithms specified in the paper lightly. If we do, we're running the risk of creating something that is not secure.

> Also, is there some property of binding all of the discharges to the root that you're relying on for a particular application?

It's crucial that all implementations do the binding in the same way, otherwise macaroon implementations are not interchangeable.

**Comment by ecordell** [comment]
> It's crucial that all implementations do the binding in the same way, otherwise macaroon implementations are not interchangeable.

I agree, just want to make sure we converge on the same correct implementation. 

> In general, I think we should be following the macaroon algorithms specified in the paper.

Also totally agreed, I think we're just reading and understanding the paper differently.

```
assert (∃M' ∈ 𝓜 : M'.id = cId ∧ M'.Verify(TM, cK, 𝒜, 𝓜))
```

As you point out, this line is the crucial one, re-using `TM` instead of `M` for the recursion.

But I think it's important to go back to the reasoning for the binding process:

>While making an access request, a client is required to provide an authorizing macaroon along with discharge macaroons for the various embedded third-party caveats. These discharge macaroons are powerful holder-of-key proofs that may be used to satisfy obligations in any and all macaroons that embed the corresponding third-party caveat identifier that uses the same root key.
>In particular, an attack is possible if the client accidentally makes a request to a principal other than the original target (perhaps by falling prey to phishing). In this case, this other principal can maliciously re-use any discharge macaroons it receives to discharge third-party caveats embedded in macaroons for itself, thereby authorizing itself using contextual caveat discharges from the client. To prevent such malicious re-use, all discharge macaroons are required to be bound to the authorizing macaroon before being sent along with a request to the target.

Binding to the root (`TM`) prevents the verifying entity from re-using discharge macaroons for other things.

Binding to the parent, though, prevents end-users from re-using nested discharge macaroons. If macaroon `M` requires a discharge `N` which requires a discharge `P`, then if the user of `M` requests `N` from a discharging service, that service can collect `P` and bind it to `N` before passing both to the holder of `M`. This is what I meant by "encapsulation" before.

I think both properties are probably desirable, so I think this option:

```python
discharge1 = root.prepare_for_request(discharge1)
discharge2 = root.prepare_for_request(discharge1.prepare_for_request(discharge2))
```

May actually be the one we want. This could be implemented nicely by having `prepare_for_request`
take a list of macaroons instead of a single macaroon.

As for security, I would note that the binding/signature modification is only required for re-use prevention and has no bearing on other properties of macaroons. I reviewed [this paper](https://cs.nyu.edu/media/publications/TR2013-962.pdf) again to make sure I wasn't missing something.

**Comment by rogpeppe** [comment]
> If macaroon M requires a discharge N which requires a discharge P, then if the user of M requests N from a discharging service, that service can collect P and bind it to N before passing both to the holder of M. This is what I meant by "encapsulation" before.

In general, I believe that the client is meant to be responsible for collecting all discharge macaroons, I believe so this is a pattern I'm not sure we'd want to encourage.

Also, note that the attack only works if the third party that adds the caveat re-uses a root key, which I'm guessing is fairly unusual.

I'd suggest that we change the implementation to match what the paper specifies (I'm fairly sure that's unambiguous) and you could perhaps consider supporting the other kind of binding as an optional extra. For the time being, I think that being compatible with the paper and all other current implementations is worthwhile.

**Comment by rogpeppe** [comment]
I guess it's worth pointing out that the current pymacaroons imlementation isn't the one you suggested above *or* the one in the paper - it is more insecure than both AFAICS.

**Comment by ecordell** [comment]
> I'd suggest that we change the implementation to match what the paper specifies (I'm fairly sure that's unambiguous) and you could perhaps consider supporting the other kind of binding as an optional extra. For the time being, I think that being compatible with the paper and all other current implementations is worthwhile.

That sounds good to me, I'll go ahead and merge your PR now and follow up later.

**Comment by rescrv** [comment]
It looks like I'm a bit late to the discussion, but I'd like to add a little bit about the recursive implementation vs binding all macaroons with the root.

The idea of binding for a request is to allow the user to take a set of macaroons they've collected, add caveats to the root macaroon that are specific to the request (e.g., limiting it to being valid for a GET http://example.org/route/ in the next 5s from 192.168.1.10) and then binding all macaroons to that route so that none of the macaroons can be used separate from each other.  The root requires others to be valid to verify, and the others are intricately tied to the root.  The same is true even if no additional caveats are added to the root before the request.  The discharge macaroons are not usable with any other root macaroon.  From a security perspective, they cannot fall into the hands of anyone else and be used for anything other than replaying the original request.  And with sufficient caveats, this is much more secure than other schemes.

When you say,

> Binding to the parent, though, prevents end-users from re-using nested discharge macaroons. If macaroon M requires a discharge N which requires a discharge P, then if the user of M requests N from a discharging service, that service can collect P and bind it to N before passing both to the holder of M. This is what I meant by "encapsulation" before.

In this case, the service generating N should not make it rely upon a discharge P without fully trusting the user to hold both N and P.  In a robust implementation, the root key of the third party caveat should be random (I think most libs provide a tool to give a recommended secret---if they don't they should (and I'll add one to libmacaroons if I'm speaking without acting)), and it is securely encrypted using the signature from the caveat immediately preceding the third party caveat.  A poorly implemented discharge service (and I'm betting it's very easy to implement one of these) could be asked to give a discharge N for which the user knows the secret used to construct N.  From there, it can look at all of N's caveats and compute the root for P along the way, stripping the encapsulation.

Of course, this same computation happens during verification too which means that if the user cannot be trusted to hold N, P without some "encapsulation" that protects them (it doesn't), the services trusted by the user where N, P will be used as part of a proof should not be trusted either, for they will be able to undo all the encapsulation.

It is an anti-pattern to have a discharge service generating third-party caveats and providing a discharge macaroon for those caveats, unless the all macaroons are locally constructed.  When this is the case, the macaroons are safe to pass back without any "encapsulation".  The user could just as easy restrict their own context by creating their own proof tree with the same first party caveats---the caveats, after all, are just plain text---and third party secrets that use a different root key to point to copied macaroons.  An invariant of all macaroon verifiers is that adding a caveat will never allow an unauthorized request to become authorized, so there can never be a case where the "original" caveat would succeed but a copy should not.

**Comment by ecordell** [comment]
Thanks for discussion @rescrv

I am still convinced that the ideal solution binds both to the parent and the root.

> Of course, this same computation happens during verification too which means that if the user cannot be trusted to hold N, P without some "encapsulation" that protects them (it doesn't), the services trusted by the user where N, P will be used as part of a proof should not be trusted either, for they will be able to undo all the encapsulation.

The encapsulation I was referring to is specifically a construction-time property. Macaroons constructed with HMAC of course means that a verifier (root key holder) can build any macaroon with that key that they wish to.

> A poorly implemented discharge service (and I'm betting it's very easy to implement one of these) could be asked to give a discharge N for which the user knows the secret used to construct N. From there, it can look at all of N's caveats and compute the root for P along the way, stripping the encapsulation.

But a properly implemented discharge service could do this correctly? Without binding to the parent it's not even an option.

> It is an anti-pattern to have a discharge service generating third-party caveats and providing a discharge macaroon for those caveats, unless the all macaroons are locally constructed.

I'm not sure it's an anti-pattern outside of what current macaroon implementations can do and are used for. If any implementation supported structural caveats, discharges could become much more interesting ("Expect discharge N, but N must have at least one discharge from (P, Q, R)")

I guess if I needed to sum up my position on this: binding to both the root and the parent is most flexible for users and at least as safe as just binding to the root.

**Comment by rogpeppe** [comment]
> I guess if I needed to sum up my position on this: binding to both the root and the parent is most flexible for users and at least as safe as just binding to the root.

Re-using third party caveat ids is an optimisation. If dischargers avoid that optimisation when adding third party caveats (and I haven't seen any argument as to why the optimisation might be important), then the problem your bind variant is addressing does not exist.

If you have a discharger that does unwisely reuse caveat ids, my understanding of @rescrv's argument is something like this.

Here's my understanding of the flow you're suggesting.

	TS:
		M := new M(k1).addThird(Discharger1, k2)
	TS → Client:
		M
	Client → Discharger1:
		thirdPartyCaveatId(M)
	Discharger1:
		DM1 := new M(k2).addThird(Discharger2, reusedKey)
	Discharger1 → Client:
		DM1
	Client → DischargeService:
		DM1
	DischargeService → Discharger2:
		thirdPartyCaveatId(DM1)
	Discharger2:
		DM2 := new M(reusedKey)
	Discharger2 → DischargeService:
		DM2
	DischargeService:
		DM2' = DM1.bindForRequest(DM2)
	DischargeService → Client
		DM2'
	Client:
		DM1' = M.bindForRequest(DM1)
		DM2'' = M.bindForRequest(DM2')
	Client → TS:
		M, DM1', DM2''

Objective: client wants to be to reuse DM2 for another macaroon.

Note: DischargeService cannot necessarily know what the target
service is. That is, it's possible that TS is also Client.

So, to reuse DM2 for another macaroon, Client also acts as
TS and goes through the above steps until it has acquired DM1.
Then it can trivially obtain reusedKey because it is privy
to M's root key.

Since it knows reusedKey, it can now reuse DM2 by computing
the signature of DM2 starting from reusedKey, giving it the
unbound version of DM2, which it can then use to discharge
any new third party caveat added by Discharger1 that reuses the
same root key.
